### ISSUE TITLE
This is being abused

### ISSUE THREAD

**Issue by NanderTGA** [Itroublve/Token-Browser-Password-Stealer-Creator#14]
Hi,

I found a malware from this discord server: [https://discord.gg/dv4jg2g3](url), and I decompiled it.
I found it downloading and executing files from this repository.
This is being used against people who don't realise free nitro is impossible.
The decompiled source code can be found at [https://www.decompiler.com/jar/81b093fd125b4f909f61d8a0f218725b/Gen.exe/download.cs](url)
I'll be telling the discord trust and safety team about this malware soon.
I would recommend making this repository private because this is only gonna be abused

**Comment by A5rocks** [comment]
+1, found this in the wild too. Perhaps add a small check on whether this script should run so the skids don't abuse it?

**Comment by iiTrauma** [comment]
[this project / repo was on some news or yt videos, so **this is kinda already knew by some ppl which can abuse it**](https://www.bleepingcomputer.com/news/security/new-troublegrabber-discord-malware-steals-passwords-system-info/)

If you tell discord ToS team they cant do something, since most of responses are automated ¯\_(ツ)_/¯
